### PR TITLE
One MatrixScheduler for every client

### LINKED ISSUE #18: ClientFactory creates a single clientScheduler for all its clients
A result of lots of debugging on my slack bridge (using current `develop` version of `matrix-appservice-bridge`), the bridge's own bot intent sometimes gets confused into sending messages out claiming to be one of its ghost users. This results in synapse errors:

```
[-] PUT http://localhost:7680/_matrix/client/r0/rooms/!dcwkeyJKpnOhTPFAWk%3Alocalhost%3A8080/send/m.room.message/m1473177931754.1 (@slack_leonerd:localhost:8080) Body: {"body":"@leo:localhost:8080:  -r=!vvBXjnizurxkUPkLLv:localhost:8080","msgtype":
[-] PUT http://localhost:7680/_matrix/client/r0/rooms/!dcwkeyJKpnOhTPFAWk%3Alocalhost%3A8080/send/m.room.message/m1473177931754.1 (@slack_leonerd:localhost:8080) HTTP 403 Error: {"errcode":"M_FORBIDDEN","error":"User @slack_leonerd:localhost:8080 not in room !dcwkeyJKpnOhTPFAWk:localhost:8080 (None)"}
Unhandled rejection M_FORBIDDEN: User @slack_leonerd:localhost:8080 not in room !dcwkeyJKpnOhTPFAWk:localhost:8080 (None)
```

### PR DESCRIPTION
**Pull request by leonerd**
Pass a scheduler builder function in to client factory rather than a single scheduler directly

Fixes #18

### CODE REVIEW

**Comment by Kegsay** [comment]
ok to test

File: lib/bridge.js [hunk 1]
```diff
@@ -190,7 +190,9 @@ Bridge.prototype.run = function(port, config, appServiceInstance) {
         appServiceUserId: (
             "@" + self.opts.registration.sender_localpart + ":" + self.opts.domain
         ),
-        clientScheduler: new MatrixScheduler(retryAlgorithm, queueAlgorithm)
+        clientSchedulerBuilder: function() {
+            new MatrixScheduler(retryAlgorithm, queueAlgorithm)
```
Comment (Kegsay) [inline lib/bridge.js]: `return` please :)

Comment (Kegsay) [inline lib/bridge.js]: and `;`

File: lib/components/client-factory.js [hunk 2]
```diff
@@ -25,7 +25,7 @@ function ClientFactory(opts) {
     //      user_id: Client
     //  }
     };
-    this._clientScheduler = opts.clientScheduler;
+    this._clientSchedulerBuilder = opts.clientSchedulerBuilder;
```
Comment (Kegsay) [inline lib/components/client-factory.js]: Default to `function(){}` please :)

Comment (Kegsay) [inline lib/components/client-factory.js]: `this._clientSchedulerBuilder = opts.clientSchedulerBuilder || function() {};`

**Comment by Kegsay** [comment]
Otherwise LGTM! Thanks!

File: lib/bridge.js (hunk 1 above)
Comment (leonerd) [inline lib/bridge.js]: Done f075106 and 6704f07

File: lib/components/client-factory.js (hunk 2 above)
Comment (leonerd) [inline lib/components/client-factory.js]: Done 58ec405
